// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace VirtusFitWeb.DAL.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20201017173214_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("BLL.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<int>("Fiber")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<int>("PortionQuantity")
                        .HasColumnType("int");

                    b.Property<string>("PortionUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Salt")
                        .HasColumnType("float");

                    b.Property<int>("Sugar")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Carbohydrates = 37.5,
                            Energy = 179,
                            Fat = 0.20999999999999999,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 50,
                            PortionUnit = "g",
                            ProductName = "Bio Spaghetti ",
                            Protein = 5.5,
                            Quantity = 500,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 2,
                            Carbohydrates = 1.1299999999999999,
                            Energy = 181,
                            Fat = 13.5,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 75,
                            PortionUnit = "g",
                            ProductName = "Naturaplan Mozzarella",
                            Protein = 14.25,
                            Quantity = 150,
                            Salt = 0.38,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 3,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "g",
                            ProductName = "Caffè Mauro - Roasted organic coffee blend",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 4,
                            Carbohydrates = 0.75,
                            Energy = 197,
                            Fat = 15.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 75,
                            PortionUnit = "g",
                            ProductName = "Naturaplan Bio Mozzarella ",
                            Protein = 15.0,
                            Quantity = 450,
                            Salt = 0.29999999999999999,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 5,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "g",
                            ProductName = "LEAVITT'S AMERICANA, Fancy Mixed Nuts",
                            Protein = 0.0,
                            Quantity = 284,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 6,
                            Carbohydrates = 0.80000000000000004,
                            Energy = 124,
                            Fat = 10.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 50,
                            PortionUnit = "g",
                            ProductName = "Vieniese Sausages",
                            Protein = 8.0,
                            Quantity = 200,
                            Salt = 0.90000000000000002,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 7,
                            Carbohydrates = 1.5,
                            Energy = 184,
                            Fat = 16.199999999999999,
                            Fiber = 4,
                            IsFavourite = false,
                            PortionQuantity = 30,
                            PortionUnit = "g",
                            ProductName = "Naturaplan Bio whole Almonds ",
                            Protein = 6.5999999999999996,
                            Quantity = 200,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 8,
                            Carbohydrates = 0.42999999999999999,
                            Energy = 103,
                            Fat = 9.0299999999999994,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 43,
                            PortionUnit = "g",
                            ProductName = "Naturaplan Cipollata veal",
                            Protein = 5.1600000000000001,
                            Quantity = 150,
                            Salt = 0.72999999999999998,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 9,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "g",
                            ProductName = "Jean Hervé - Almond Purée",
                            Protein = 0.0,
                            Quantity = 700,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 10,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 15,
                            PortionUnit = "g",
                            ProductName = "Raw health Bio - White Chia Seeds ",
                            Protein = 0.0,
                            Quantity = 450,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 11,
                            Carbohydrates = 7.0999999999999996,
                            Energy = 59,
                            Fat = 2.5,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 100,
                            PortionUnit = "g",
                            ProductName = "PANZANI",
                            Protein = 1.3,
                            Quantity = 400,
                            Salt = 1.1799999999999999,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 12,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "Lou mas: Sunflower oil",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 13,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "g",
                            ProductName = "Barilla: the Pesti, red pesto",
                            Protein = 0.0,
                            Quantity = 200,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 14,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "g",
                            ProductName = "Barilla: the Pesti, Calabrian",
                            Protein = 0.0,
                            Quantity = 190,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 15,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "Belle France: cider vinegar, Normandy",
                            Protein = 0.0,
                            Quantity = 750,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 16,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: orange-mango",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 17,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: pineapple",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 18,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: peach",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 19,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: Orange 100%, without pulp",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 20,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini : Fruchtcocktail",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 21,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: pink grapefruit",
                            Protein = 0.0,
                            Quantity = 1000,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 22,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: My Moment, Pink Grapefruit - Cranberry",
                            Protein = 0.0,
                            Quantity = 330,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 23,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: My Moment, Lemon-Lemon",
                            Protein = 0.0,
                            Quantity = 330,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 24,
                            Carbohydrates = 22.0,
                            Energy = 109,
                            Fat = 1.25,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 250,
                            PortionUnit = "ml",
                            ProductName = "GRANINI: 100% ORANGE",
                            Protein = 2.5,
                            Quantity = 330,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 25,
                            Carbohydrates = 27.5,
                            Energy = 114,
                            Fat = 0.5,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 250,
                            PortionUnit = "ml",
                            ProductName = "RAMSEIER: APPLE JUICE, natural",
                            Protein = 0.5,
                            Quantity = 500,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 26,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "RAMSEIER : HOCHSTÄMMER, obstsaft naturtrüe",
                            Protein = 0.0,
                            Quantity = 500,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 27,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "granini: Fruity & tingling, apple",
                            Protein = 0.0,
                            Quantity = 500,
                            Salt = 0.0,
                            Sugar = 0
                        },
                        new
                        {
                            ProductId = 28,
                            Carbohydrates = 0.0,
                            Energy = 0,
                            Fat = 0.0,
                            Fiber = 0,
                            IsFavourite = false,
                            PortionQuantity = 0,
                            PortionUnit = "ml",
                            ProductName = "CRISTALP",
                            Protein = 0.0,
                            Quantity = 500,
                            Salt = 0.0,
                            Sugar = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
